name: BuildAndTest

on:
  workflow_dispatch:

jobs:
 build:
    name: Build and Test default scheme using iPhone simulator
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: '14.2'
      - name: Install GPG
        run: brew install gnupg
      - name: Install xcbeautify
        run: brew install xcbeautify
      - name: Decrypt large secret
        run: ./provisioning/import_provisioning.sh
        env:
          PROVISIONING_PASSWORD: ${{ secrets.UNLOCK_CERTIFICATE }}
      - name: Build archive
        run: xcodebuild -sdk iphoneos -project SampleJokes.xcodeproj -configuration Release -scheme SampleJokes -derivedDataPath DerivedData -archivePath DerivedData/Archive/SampleJokes archive | xcbeautify --renderer github-actions
      - name: Export Archive
        run: xcodebuild -exportArchive -archivePath DerivedData/Archive/SampleJokes.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath DerivedData/ipa
      - name: Dump file hierarchy
        run: ls -R
    
