name: BuildAndTest

on:
  workflow_dispatch:

jobs:
 build:
    name: Build and Test default scheme using iPhone simulator
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: '14.2'
      - name: Build and export IPA
        uses: yukiarrr/ios-build-action@v1.11.0
        with:
          project-path: SampleJokes.xcodeproj
          scheme: "SampleJokes"
          export-method: "development"
          p12-base64: ${{ secrets.APPLE_DEVELOPMENT_CERTIFICATE }}
          mobileprovision-base64: ${{ secrets.APPLE_DEVELOPMENT_PROVISIONING_PROFILE }}
          certificate-password: ${{ secrets.UNLOCK_CERTIFICATE }}
          code-signing-identity: "Apple Development: Pran Kishore (XF6ZUP2XAH)"
          export-options: "ExportOptions.plist"
          team-id: "5KSQYC3V4Y"
    
