name: DisptachInputCheck

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: 'AWS SDK Check'
        default: 'QA'
        options: 
        - DEV
        - QA
        - PROD
      message:
        type: string
        required: true
      use-emoji:
        type: boolean
        default: true
        description: Upload to TestFlight
      environment:
        description: 'Environment to build'
        type: environment
      debug:
        type: boolean
        default: true
        description: Enable debug mode
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "ðŸ¥³"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
    - name: Check Environment Variable
      run: echo "My key is $TESTFLIGHT_KEY"
    - name: Print environment name
      run: echo "${{ github.env }}"
    - name: Check Repo Environment Variable
      run: echo "My repo key is $HOCKEY_KEY"
